version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
    container_name: nuxt_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
